CREATE TABLE Users
(
    id         INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    username   VARCHAR(255) NOT NULL
);

ALTER TABLE users ADD COLUMN admin BOOLEAN DEFAULT FALSE;
ALTER TABLE users DROP COLUMN admin;